server:
  port: 8080

spring:
  application:
    name: emqx-to-rabbit

  # RabbitMQ (Lee variables de entorno)
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    virtual-host: /
    publisher-confirm-type: correlated

# Nombres de colas (puedes dejarlos fijos o usar variables si quisieras cambiarlos)
app:
  rabbitmq:
    queue: "camara-queue"
    exchange: "exchange-camera"
    routing-key: "camara-routing-key"

# MQTT (Lee variables de entorno)
mqtt:
  brokerUrl: ${MQTT_BROKER_URL}
  clientId: ${MQTT_CLIENT_ID}
  username: ${MQTT_USERNAME}
  password: ${MQTT_PASSWORD}
  # El tópico usamos el comodín # para producción también
  topic: "Bit-iot/+/+/+/Camara/#"

logging:
  level:
    root: WARN # Menos ruido en producción
    com.bitiot.volga3: INFO # Solo logs importantes