
# Configuración para el perfil 'dev' (local)
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest   # usuario y contraseña para desarrollo en http://localhost:15672/#/
    password: guest
    virtual-host: /
    publisher-confirm-type: CORRELATED # para confirmar la publicación de mensajes

mqtt:
  brokerUrl: tcp://206.189.183.181:1883
  clientId: emqx-to-rabbit-client
  username: pruebas_python
  password: python2023
  #topic: "Bit-iot/#"

logging:
  level:
    org.springframework.amqp.rabbit: INFO