server:
  port: 8080

spring:
  application:
    name: emqx-to-rabbit
  profiles:
    active: dev # Está activo por defecto para correr en local

  # Configuración de la app que es igual en todos los entornos

app:
  rabbitmq:
    queue: "camara-queue"
    exchange: "exchange-camera"
    routing-key: "camara-routing-key"

mqtt:
  topic: "Bit-iot/#"

logging:
  level:
    root: INFO
    com.bitiot.volga3: INFO # Log del propio código