server:
  port: 8080

spring:
  application:
    name: emqx-to-rabbit
  rabbitmq:
    host: 181.205.53.2   # O se puede poner el hostname del servidor en stage
    port: 5672
    username: bitiotadmin   # usuario para stage
    password: 817107V01643bitiot*   # contraseña para stage
    virtual-host: /
    publisher-confirm-type: CORRELATED

app:
  rabbitmq:
    queue: "camara-queue"
    exchange: "exchange-camera"
    routing-key: "camara-routing-key"

mqtt:
  brokerUrl: tcp://206.189.183.181:1883
  clientId: emqx-to-rabbit-client
  username: pruebas_python
  password: python2023
  topic: "Bit-iot/#"

logging:
  level:
    root: WARN
    #org.springframework.web: DEBUG
    org.springframework.amqp.rabbit: DEBUG
    #org.springframework.integration: DEBUG # Para ver logs de Spring Integration
    com.bitiot.volga3: DEBUG # Log del propio código