# Configuraci√≥n para el perfil 'stage' (lee variables de entorno)
spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    virtual-host: /
    publisher-confirm-type: CORRELATED

mqtt:
  brokerUrl: ${MQTT_BROKER_URL}
  clientId: ${MQTT_CLIENT_ID}
  username: ${MQTT_USERNAME}
  password: ${MQTT_PASSWORD}

logging:
  level:
    root: WARN
    org.springframework.amqp.rabbit: DEBUG
    com.bitiot.volga3: DEBUG