server:
  port: 8080

spring:
  application:
    name: emqx-to-rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest   # usuario y contraseña para desarrollo en http://localhost:15672/#/
    password: guest
    virtual-host: /
    publisher-confirm-type: CORRELATED # para confirmar la publicación de mensajes

app:
  rabbitmq:
    queue: "camara-queue"
    exchange: "exchange-camera"
    routing-key: "camara-routing-key"

mqtt:
  brokerUrl: tcp://206.189.183.181:1883
  clientId: emqx-to-rabbit-client
  username: pruebas_python
  password: python2023
  topic: "Bit-iot/#"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.amqp.rabbit: DEBUG
    org.springframework.integration: DEBUG # Para ver Spring Integration
    com.bitiot.volga3: DEBUG # Log del propio código